changing generate_api_warszawa_url and some paths
klepper24/WarsawPublicTransport pull request #11
Opened 2022-11-29 10:42 UTC by Maryl12342

Hello @mgierm , @klepper24, please review my changes.

2022-11-29 10:52 UTC, klepper24 approved these changes
looks fine for me

2022-12-05 14:18 UTC, Maryl12342 commented
@mgierm, @meg25ellele, @klepper24, you can take a look on my changes: 
4c23be333b59d512f0e36a894dcb7bc0192af595

2022-12-05 14:54 UTC, mgierm requested changes
Good job generally :clap: 
I added few suggestions mostly about naming objects and some improvements.
I also noticed that few changes where reverted (pep8 fixes), so maybe you just forgot to pull last changes from `main` branch.

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/utils.py
> +        return response.status_code, response.json()
```suggestion
        response.raise_for_status()
        return response.json()
```
If there is a call for `raise_for_status`, there is rather no need to return the status code (uneless we really need to handle different 2xx statuses in the executed code). Take a look at the [source of `raise_for_status`](https://requests.readthedocs.io/en/latest/_modules/requests/models/#Response.raise_for_status)

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/utils.py
> +    def get_busestrams(self, resource_id=None, type=None):
I suggest to rename parameter `type` to something different, like `resource_type` - `type` is a [built-in function](https://docs.python.org/3/library/functions.html#type), so better to not overwrite it.

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/utils.py
> +        return self._busestrams
```suggestion
        return self._get(ApiWarsawUrl.ENDPOINT_BUSESTRAMS, params)
        
```
The `_busestrams` is not used across the class, so we don't need to define it.

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/utils.py
> +class ApiWarsawUrl:
Maybe just `ApiWarsaw`, or `WarsawApi`? :wink:

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/delays_processing.py
> +    status, json_response = api.get_busestrams(resource_id=RESOURCE_ID, type=2)
If you apply my suggestion to not return status code, then you could remove the following `if` statement.

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/delays_processing.py
> +        conf={"spark.master":settings.SPARK_MASTER},
```suggestion
        conf={"spark.master": settings.SPARK_MASTER},
```

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/general_data_import.py
> +    _, json_string = api.get_dbstore(id=RESOURCE_ID)
If you apply my suggestion to not return status code, then you could remove the `_` variable.

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/delays_processing.py
> +        bash_command=f'mkdir -p {settings.SPARK_OUT_DIR}ARCHIVE/ & mv {settings.TRAM_FOLDER}* {settings.SPARK_OUT_DIR}ARCHIVE/ & rm -R {settings.TRAM_FOLDER}'
Reverted change, accidently I guess.

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/delays_processing.py
> +    start >> task_save_tram_gps >> spark_job >> task_move_to_archive >> end
Reverted change (no newline an the end of file), accidently I guess.

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/delays_processing.py
> +        filename = f'{settings.TRAM_FOLDER}tram{settings.TODAY_TIME}.json'
Reverted change, accidently I guess.

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/delays_processing.py
> +        application="/opt/spark/execution_scripts/delays_proc.py", # Spark application path created in airflow and spark cluster
Reverted change (too many chars in a line), accidently I guess.

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/general_data_import.py
> +
```suggestion

```

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/settings.py
> +SPARK_OUT_DIR = '/opt/spark/execution_scripts/'
Reverted change, accidently I guess.

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/settings.py
> +TODAY_DATETIME = datetime.now().astimezone(TO_ZONE)
Reverted change, accidently I guess.

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/settings.py
> +TRAM_FOLDER = f'{SPARK_OUT_DIR}{TODAY_DATE}/'
Reverted change, accidently I guess.

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/utils.py
> +    def get_dbstore(self, id=None):
I suggest to rename parameter `id` to something different, like `resource_id` - `id` is a [built-in function](https://docs.python.org/3/library/functions.html#id), so better to not overwrite it.

2022-12-05 14:54 UTC, mgierm commented on orchestrator/dags/settings.py
> +MONGO_HOST = 'git_mongo-python_1'
```suggestion
MONGO_HOST = 'git_mongo-python_1'

```
Reverted change, accidently I guess.

2022-12-12 12:16 UTC, merged