Mostr docker postgres
klepper24/WarsawPublicTransport pull request #15
Opened 2023-01-31 10:15 UTC by Maryl12342

Hello, please review my changes. 
Regarding removing lines with .env in docker-compose- I did it because I got following error:
"ERROR: Couldn't find env file: *****\Documents\GIT\.env"

2023-01-31 10:45 UTC, mgierm commented
> Hello, please review my changes. Regarding removing lines with .env in docker-compose- I did it because I got following error: "ERROR: Couldn't find env file: *****\Documents\GIT.env"

Please copy [.example.env](https://github.com/klepper24/WarsawPublicTransport/blob/main/.example.env) content into `.env` file which you should create in the project root directory (next to `.example.env`). Let me know if it helps or not.

2023-01-31 14:41 UTC, Maryl12342 commented
@mgierm it worked out, thanks :) I restored lines with .env in docker-compose.

2023-02-01 08:55 UTC, mgierm reviewed
Looks good overall :+1: Just a few little comments.

2023-02-01 08:55 UTC, mgierm commented on postgresdb/WarsawTransportState.sql
> +  "full_name" int,
Just to double-check - is it really `int`?

2023-02-01 08:55 UTC, mgierm commented on docker-compose.yml
> +      - internal-network
```suggestion
      - internal-network
```

2023-02-01 08:55 UTC, mgierm commented on docker-compose.yml
> +
```suggestion
```

2023-02-02 14:52 UTC, Maryl12342 commented
@meg25ellele @klepper24  @mgierm, I uploaded files with latest db schema and with minor changes in docker-compose file. Please take a look :)

2023-02-03 07:50 UTC, mgierm requested changes

2023-02-03 07:50 UTC, mgierm commented on docker-compose.yml
> +        - internal-network
```suggestion
        - internal-network
```

2023-02-03 07:50 UTC, mgierm commented on docker-compose.yml
> +
```suggestion
```

2023-02-03 07:50 UTC, mgierm commented on postgresdb/WarsawTransportState.sql
> +  "is_depot" int,
It's probably the result of the mistake in the diagram - but I believe it should be `boolean` instead `int`

2023-02-03 12:53 UTC, Maryl12342 commented
Changes added.

2023-02-17 11:22 UTC, klepper24 approved these changes
cool :)

2023-02-21 16:25 UTC, merged