Adding SQLAlchemy classes
klepper24/WarsawPublicTransport pull request #17
Opened 2023-02-02 14:27 UTC by meg25ellele

2023-02-03 08:10 UTC, mgierm requested changes
It's a good piece of work in general :+1: I added few notices, most importat is that we don't need the `__init__` methods, so you can remove them without worries. 

One point which I just noticed - one week ago the new version of SQLAlchemy was released - 2.0. It changes the approach of declaring class fields, take a look -> https://docs.sqlalchemy.org/en/20/orm/mapping_styles.html#orm-declarative-mapping

But I think we can stick to the previous version 1.4.x. (just for learning purposes).

2023-02-03 08:10 UTC, mgierm commented on orchestrator/dags/sql_alchemy_classes.py
> +    create_at = Column(DateTime)
```suggestion
    created_at = Column(DateTime)
```

2023-02-03 08:10 UTC, mgierm commented on orchestrator/dags/sql_alchemy_classes.py
> +    is_depot = Column(Integer)
`is_depot` probably should be a `Bool`.

2023-02-03 08:10 UTC, mgierm commented on orchestrator/dags/sql_alchemy_classes.py
> +    def __init__(self, unit_post: int, full_name: str, stop_longitude: float, stop_latitude: float, street: str,
These `__init__` methods are not necessary. All of them could be removed.

2023-02-03 08:10 UTC, mgierm commented on orchestrator/dags/sql_alchemy_classes.py
> +base = declarative_base()
```suggestion
Base = declarative_base()
```

`declarative_base` is a Class constructor, so the name `Base` should be named like a class.

2023-02-03 09:27 UTC, meg25ellele commented
@mgierm @klepper24 @Maryl12342 I added some changes related to Mikolaj comment

2023-02-03 09:35 UTC, mgierm approved these changes
:+1:

2023-02-17 11:19 UTC, klepper24 approved these changes

2023-02-21 14:05 UTC, merged