Sql alchemy stops
klepper24/WarsawPublicTransport pull request #19
Opened 2023-03-18 18:47 UTC by Maryl12342

2023-03-22 07:29 UTC, klepper24 commented on docker-compose.yml
> +  postgres-db-bitnami-volume:
Is it needed to have 2 volumes? If not, please remove one of them.
In general, I'm not sure if lines 373-375 are needed at all.

2023-04-13 12:24 UTC, Maryl12342 commented
@klepper24 , @meg25ellele please review, my changes.

2023-04-17 07:26 UTC, klepper24 requested changes
Because mongo_to_postgres.py it's not a DAG yet, I recommend creating a new folder for such scripts which will be implemented as a DAG in future.

2023-04-17 07:26 UTC, klepper24 commented on orchestrator/dags/mongo_to_postgres_stops.py
>  import os
I think it's no longer needed since you import variables from settings

2023-04-17 13:57 UTC, Maryl12342 commented
Changes added.

2023-04-17 13:58 UTC, klepper24 approved these changes

2023-04-17 13:59 UTC, merged